* Computing Magic -- A Modular Curriculum
  
A [[https://github.com/GregDavidson/computing-magic][Computing Magic Project]] Curriculum.

Think of this as a Montessori-style classroom for learning. The material is
broken up into Modules which contain projects along with opportunities to create
your own projects. After the first module you can do the others in any order
that makes sense to you. There are many links to additional enriching content.

Modules marked with FUTURE contain the plans for that module's eventual form.
They are currently heavy on information and light on activities. If you choose
to explore them you'll need to fill in your own ways to practice and/or ask for
suggestions. You would thereby be helping in that module's development.

When a module changes status, e.g. from FUTURE to NEW to unmarked you should
expect major improvements. *If you read one of the earlier versions, check back
to see those improvements!* These modules were in conjunction with Group
Sessions. At some point I intend to create some short videos to replicate some
of the enrichment pieces that were a part of those meetings.

*** Module and Session Notes

- [[file:Module-1/module-1.org][Module 1: Functional Programming]]
We begin an Open Lab with a Tutorial for *learning Lisp / Scheme / Racket by
writing functions which compute pictures*.

- [[file:Module-1a/module-1a.org][Module 1a: 2D and 3D Functional Art]]
After a brief presentation, this will be an Open Lab for *Making Functional
Visual Art* with the =pict= and =pict3d= packages

- [[file:Module-1b/module-1b.org][Module 1b: Imperative 2D Art]]
After a brief presentation, this will be an Open Lab for *Creating Visual Art
using Imperative Turtle Graphics!*

- [[file:Module-1c/module-1c.org][New Module 1c: Animation and Game Design]]
Exploring techniques for *Animation & Interactive Graphics & Game Design!*

- [[file:Module-2/module-2.org][Module 2: Software Development Power Tools]]
Exploring more powerful software development tools.  *Installing and setting
up a more powerful development environment!*

- [[file:Module-3/module-3.org][Module 3: Using the Power Tools with Your Projects]]
Incorporating the New Tools for your Art or other projects.

- [[file:Module-4/module-4.org][NEW Module 4: Web, Systems and Network Programming]]
Learning *Systems and Network Programming* by writing a Web Server using the
Software Tools learned so far.

- [[file:Module-5/module-5.org][NEW Module 5, SQL and Relational Design]]
Learning the power of *SQL* and the /Relational Model/ for Programming and
Persistence!

- [[file:Module-6/module-6.org][FUTURE Module 6, Putting it All Together]]
Creating an ambitious Project to use Web, Graphics, Lisp and SQL.
An opening for *Creativity and Software Design*.

- [[file:Module-7/module-7.org][FUTURE Module 7, Knowledge-Based AI Technology]]
*Getting your computer to understand your domain*: Major magical AI technologies
with learning avenues. Where Machine Learning fits in with Knowledge-Based AI.
