* ==> START HERE for Computing Magic

Computing Magic is a [[https://github.com/GregDavidson/loel/blob/main/Devel/creating-curricula.org][Curriculum]] of the [[https://github.com/GregDavidson/loel#readme][League of Extraordinary Learners]].

This curriculum is under continuous development by its participants!

** TL;DR

The main path through this curriculum is a set of Modules. After completing the
first module, the other modules can be explored in a flexible order.

- [[file:Modules/README.org][Go immediately to the Modules]]
- Or continue reading for more context!

** What is Computing Magic?

Fasten your seat-belt and watch [[https://www.youtube.com/watch?v=6avJHaC3C2U][The Art of Code]] video on YouTube!
- The first parts of this amazing video may blow your mind!
- Computing Magic gives you the power to create and explore Infinite Worlds!

Mastering /Computing Magic/ will allow you to get computers to do with ease what
would be hopelessly difficult to do using ordinary technologies.

With Computing Magic we can design
- Fabulous Machines
- Customized Biological Organisms
- Fascinating and Enlightening Immersive Games
- Intelligent assistants to handle all the boring things
- Applications which Make You More Intelligent
- and much more!

We can explore our creations with /Virtual Reality/, share them with
/Collaborative Computing/ and materialize them in the Real World with
- 3D Printers
- DNA sequencers
- Hybrid AI Frameworks
- Robots
- Networks
- etc.

Instead of creating digital artifacts manually, e.g. with /Graphical User
Interfaces/ and/or /Interactive Editors/, Computing Magic we can often tell a
Computer Program /what we want/ (the specification) and have the Computer
Program figure out /how to do it/.

Many of the Pioneers of computing were Computing Magicians - by necessity!
Almost nothing existed so they had to invent what they needed to fulfill their
visions. The vast number of tools, e.g. apps and libraries available today tend
to suppress the vision of most users and developers. But used creatively, with
the right understandings, the best of those tools can make Computing Magic more
accessible than it's ever been!

This repository contains the beginning of a fast-path curriculum for learning
Computing Magic for those who yearn for unlimited possibilities!

** Curriculum Resources

- [[file:Modules/README.org][the Main Modules]]
- [[cm-examples.org]]
- [[cm-curriculum.org]]
- [[cm-distinctions.org]]
- [[cm-quotes.org]]

We'll be trying to keep the Computer Programming Languages which we use to a
practical minimum.
- See [[file:Languages-And-Platforms/choosing-languages.org][Which Computer Languages Matter?]]

Recommended related Repositories
- [[https://github.com/GregDavidson/on-computing#readme][On Computing]]
- [[https://github.com/GregDavidson/on-lisp#readme][On Lisp]]

To start your journey with /this curriculum/
- [[file:Modules/README.org][Browse the Modules README]]

** Acknowledgments and Invitation

I am very grateful for the participation of the brave and hardy Alpha
participants from [[https://docs.google.com/document/d/1qSUTfoOXDAfoH-OF_7N7kEzlp5-F4nf0JP3BzgppDY0/edit][The Limitless Fellowship]] in 2021 and the similarly intrepid
Beta participants from [[https://mars.college][Mars College]] in 2022 who have inspired and contributed to
this project.

We invite you to participate by
- Using thise materials for your own benfit as a /Learner/
- Assisting New Learners as /Peer Facilitators/
- Improving these materials

You can help improve these materials by
- Submitting Issues
- Forking the repository
- Because all of our materials are Open Source (AGPL)
      - You can make changes in your copy
      - Share them with us via a pull request
      - /We will need a copyright assignment from you to accept it/

Most of our Documents are textfiles using [[https://orgmode.org][OrgMode]] markup notation. =OrgMode= is
much more powerful than the more commonly used =Markdown=. Github has some
support for =OrgMode= as do several popular programming environments. When
you're ready to unlock the full power of =OrgMode= you'll want to learn [[https://github.com/GregDavidson/computing-magic/blob/main/Software-Tools/Emacs/emacs-readme.org][Emacs]].

This is [[https://github.com/GregDavidson/loel/blob/main/Short-Works/open-content.org][Open Content]] from the [[https://github.com/GregDavidson/loel#readme][League of Extraordinary Learners]]!
