* Computing Magic

A [[https://github.com/GregDavidson/loel/blob/main/Devel/creating-curricula.org][Curriculum]] of the [[https://github.com/GregDavidson/loel#readme][League of Extraordinary Learners]].

This curriculum is under continuous development by its participants!

** TL;DR

The main path through this curriculum is a set of Modules. After completing the
first module, the other modules can be explored in a flexible order.
- [[file:Modules/README.org][Go to the Modules]]

** What is Computing Magic?

Fasten your seat-belt and watch the first 40 minutes of [[https://www.youtube.com/watch?v=6avJHaC3C2U][The Art of Code]]!
- This amazing video barely scratches the surface of what's available from
  Computing Magic!

/Computing Magic/ is leveraging the power of computers and software to do with
ease what would be hopelessly difficult in the real world. With Computing Magic
we can design
- Fabulous Machines
- Customized Biological Organisms
- Immersive Games
- and much more!

We can explore our creations with /Virtual Reality/, share them with
/Collaborative Computing/ and materialize them in the Real World with
- 3D Printers
- DNA sequencers
- Hybrid AI Frameworks
- etc.

A key ingredient of the magic: Instead of creating digital artifacts manually,
e.g. with /Graphical User Interfaces/ and/or /Interactive Editors/, we supply
specifications and let the computer do the hard work. Specifications say /what/
we want and the computer figures out /how/ to do it.

Many of the Pioneers of computing were Computing Magicians - by necessity! The
modern surfeit of ready-made solutions and the mind-numbing complexity of most
current software obscures the possibility of Magic and Mastery from most of
today's /Users/ and /Programmers/. Yet the power of today's tools makes
Computing Magic potentially more accessible!

This repository contains the beginning of a fast-path curriculum for learning
Computing Magic for those who yearn for such!

** Curriculum Resources

- [[file:Modules/README.org][the Main Modules]]
- [[cm-examples.org]]
- [[cm-curriculum.org]]
- [[cm-distinctions.org]]
- [[cm-quotes.org]]

We'll be trying to keep the Computer Programming Languages which we use to a
practical minimum.
- See [[file:Languages-And-Platforms/choosing-languages.org][Which Computer Languages Matter?]]

Highly recommended related Repositories
- [[https://github.com/GregDavidson/on-computing#readme][On Computing]]
- [[https://github.com/GregDavidson/on-lisp#readme][On Lisp]]

To start your journey with /this curriculum/
- [[file:Modules/README.org][Browse the Modules README]]

** Acknowledgments and Invitation

I am very grateful for the participation of the brave and hardy Alpha
participants from [[https://docs.google.com/document/d/1qSUTfoOXDAfoH-OF_7N7kEzlp5-F4nf0JP3BzgppDY0/edit][The Limitless Fellowship]] in 2021 and the similarly intrepid
Beta participants from [[https://mars.college][Mars College]] in 2022 who have inspired and contributed to
this project.

We invite you to participate by
- Using thise materials for your own benfit as a /Learner/
- Assisting New Learners as /Peer Facilitators/
- Improving these materials

You can help improve these materials by
- Submitting Issues
- Forking the repository
- Because all of our materials are Open Source (AGPL)
      - You can make changes in your copy
      - Share them with us via a pull request
      - /We will need a copyright assignment from you to accept it/

Most of our Documents are textfiles using [[https://orgmode.org][OrgMode]] markup notation. =OrgMode= is
much more powerful than the more commonly used =Markdown=. Github has some
support for =OrgMode= as do several popular programming environments. When
you're ready to unlock the full power of =OrgMode= you'll want to learn [[https://github.com/GregDavidson/computing-magic/blob/main/Software-Tools/Emacs/emacs-readme.org][Emacs]].

This is [[https://github.com/GregDavidson/loel/blob/main/Short-Works/open-content.org][Open Content]] from the [[https://github.com/GregDavidson/loel#readme][League of Extraordinary Learners]]!
