* Computing Magic Roadmap

Glorious things to work on:

- Add more [[file:RESOURCES.org][General RESOURCES]]
- Create RESOURCES for Topics
- Organize the Materials for the AI Module

Current Active Projects
- Shell Scripting
- Sockets
- Animation & Games
      - Study the great tools in [[file:/home/greg/Data/Racket-Others/racket-examples-master][Racket Multimedia Game Examples]]
            - Derive some learning-paths from them
      - Study Racket Game Frameworks

** Add FAQ Drawers!

Use the Drawers feature of OrgMode to add FAQ nodes liberally through the
documents!

** Refactoring Folders, Files Adding TAGS

Push languages, platforms, tools into subdirectories

Add OrgMode TAGS to all files

Add links to all OrgMode files from INDEX.org files
List everything which links to them!

Write a script to check the validity of all links!

Cross Reference links in RESOURCES with external links in the curriculum files.
- The RESOURCES should have all the curriculum links and more
- Where else should the RESOURCES links be used?
