* Computing Magic Beta Notes

Notes from the [[https://github.com/GregDavidson/computing-magic][Computing Magic Project]] Beta Course
- [[https://mars.college][Mars College]], Q1 2022

Notes in the future are partly planning and partly materials use during the
meeting. The notes are edited after each meeting to reflect lessons learned. The
goal is to have a complete set of materials suitable for self or group learning
by the end of the quarter.

*** Meeting Notes
    
- [[file:2022-01-24-meeting-1.org][Meeting #1, Monday 24 January 2022]]
An Open Lab in which we began a Tutorial learning Lisp / Scheme / Racket by
writing functions which compute pictures. There were interruptions with
enrichment pieces.
  
- [[file:2022-01-31-meeting-2.org][Meeting #2, Monday 31 January 2022]]
A top-down review and presentation of key software development tools to come. It
became clear that the top-down format was inferior to the Open Lab format so
we're not going to do top-down any more!

- [[file:2022-02-07-meeting-3.org][Meeting #3, Monday 7 February 2022]]
An Open Lab in which we will variously be working on Computational Art and
learning Software Development Tools. There will be interruptions with enrichment
pieces and a teaser for the next session.

- [[file:2022-02-14-meeting-3.org][Meeting #4, Monday 14 February 2022]]
An Open Lab in which we some of us begin a Tutorial learning Systems and Network
Programming by writing a Web Server using the Software Tools learned so far,
while others work on Computational Art.
