* Computing Magic Beta Notes

Notes from the [[https://github.com/GregDavidson/computing-magic][Computing Magic Project]] Beta Course
- [[https://mars.college][Mars College]], Q1 2022

Notes in the future are partly planning and partly materials that may be useful
during the meeting. The notes are edited after each meeting to reflect lessons
learned. The goal is to have a complete set of materials suitable for self or
group learning by the end of the quarter.

*** Session Notes
    

- [[file:2022-01-24-meeting-1.org][Session 1, Monday 24 January 2022]]
An Open Lab in which we began a Tutorial learning Lisp / Scheme / Racket by
writing functions which compute pictures. There were interruptions with
enrichment pieces.
  
- [[file:2022-01-24-meeting-1.org][Session 1a, 2D and 3D Functional Art]]
An Open Lab in which we extend the Quick Tutorial to create Functional Art!
  
- [[file:2022-01-24-meeting-1.org][Session 1b, Imperative 2D Art]]
An Open Lab in which we extend the Quick Tutorial to create Imperative Art!
  
- [[file:2022-01-24-meeting-1.org][Session 1c, Animation and Game Design]]
An Open Lab in which we extend the Quick Tutorial to create Imperative Art!
  
- [[file:2022-01-31-meeting-2.org][Session 2, Software Development Power Tools Review]]
A top-down review and presentation of key software development tools to come. It
became clear that the top-down format was inferior to the Open Lab format so
we're not going to do top-down any more!

- [[file:2022-02-07-meeting-3.org][Session 3, Using the Power Tools with Your Projects]]
An Open Lab in which we will variously be working on Computational Art and
learning Software Development Tools. There will be interruptions with enrichment
pieces and a teaser for the next session.

- [[file:2022-02-14-meeting-3.org][Session 4, Web and Network Programming]]
An Open Lab in which we some of us begin a Tutorial learning Systems and Network
Programming by writing a Web Server using the Software Tools learned so far,
while others work on Computational Art.

- [[file:2022-02-14-meeting-3.org][Session 5, SQL and Relational Design]]
An introduction to Database Systems, SQL and the Magic of Relational
Programming.

- [[file:2022-02-14-meeting-3.org][Session 6, Putting it All Together]]
Creating an ambitious Project to use Web, Graphics, Lisp and SQL. An
introduction to Creativity and Software Design.

- [[file:2022-02-14-meeting-3.org][Session 7, Knowledge-Based AI Technology]]
Getting your computer to understand your domain: A survey with learning avenues.
Hybridizing Machine Learning and Knowledge-Based AI.
