* Computing Magic Beta Notes

Notes from the [[https://github.com/GregDavidson/computing-magic][Computing Magic Project]] Beta Course
- [[https://mars.college][Mars College]], Q1 2022

Notes in the future are partly planning and partly materials that may be useful
during the meeting. The notes are edited after each meeting to reflect lessons
learned. The goal is to have a complete set of materials suitable for self or
group learning by the end of the quarter.

*** Session Notes
    

- [[file:2022-01-24-meeting-1.org][Session 1, Monday 24 January 2022]]
An Open Lab in which we began a Tutorial *learning Lisp / Scheme / Racket by
writing functions which compute pictures*. There will be interruptions with
enrichment pieces.
  
- [[file:2022-01-24-meeting-1.org][Session 1a, 2D and 3D Functional Art]]
After a brief presentation, this will be an Open Lab for *Making Functional
Visual Art* with the =pict= and =pict3d= packages
  
- [[file:2022-01-24-meeting-1.org][Session 1b, Imperative 2D Art]]
After a brief presentation, this will be an Open Lab for *Creating Visual Art
using Imperative Turtle Graphics!*
  
- [[file:2022-01-24-meeting-1.org][Session 1c, Animation and Game Design]]
An Open Lab exploring *Animation & Interactive Graphics & Game Design!*
  
- [[file:2022-01-31-meeting-2.org][Session 2, Software Development Power Tools Review]]
Exploring more powerful software development tools.  *Installing and setting
up a more powerful development environment!*

- [[file:2022-02-07-meeting-3.org][Session 3, Using the Power Tools with Your Projects]]
Using either DrRacket or the New Tools for your Art or other projects. There
will be interruptions with enrichment pieces and a teaser for the next session.

- [[file:2022-02-14-meeting-3.org][Session 4, Web and Network Programming]]
An Open Lab in which we some of us begin a Tutorial learning *Systems and
Network Programming* in Lisp by writing a Web Server using the Software Tools
learned so far, while others work on Computational Art.

- [[file:2022-02-14-meeting-3.org][Session 5, SQL and Relational Design]]
An Open Lab in which we began a *SQL Tutorial*. We will learn the power of the
Relational Model for Programming and Persistence! There will be interruptions
with enrichment pieces.

- [[file:2022-02-14-meeting-3.org][Session 6, Putting it All Together]]
Creating an ambitious Project to use Web, Graphics, Lisp and SQL. An
opening for *Creativity and Software Design*.

- [[file:2022-02-14-meeting-3.org][Session 7, Knowledge-Based AI Technology]]
*Getting your computer to understand your domain*: Major magical AI technologies
with learning avenues. Where Machine Learning fits in with Knowledge-Based AI.
