* Computing Magic Beta Notes

Notes from the [[https://github.com/GregDavidson/computing-magic][Computing Magic Project]] Beta Course
- [[https://mars.college][Mars College]], Q1 2022

Notes on future sessions are partly a plan for that session and partly materials
that may be useful during the meeting. *The notes are edited after each meeting*
to reflect lessons learned so be sure and read them a few days later! The goal
is to have *a complete set of self-paced modules suitable for self or group
learning* by the end of the quarter. We will be exploring each module with a
Group Session.

*** Session Notes

- [[file:meeting-1.org][Session 1, Monday 24 January 2022]]
We begin an Open Lab with a Tutorial for *learning Lisp / Scheme / Racket by
writing functions which compute pictures*. There will be interruptions with
enrichment pieces.
  
- [[file:meeting-1a.org][Session 1a, 2D and 3D Functional Art]]
After a brief presentation, this will be an Open Lab for *Making Functional
Visual Art* with the =pict= and =pict3d= packages
  
- [[file:meeting-1b.org][Session 1b, Imperative 2D Art]]
After a brief presentation, this will be an Open Lab for *Creating Visual Art
using Imperative Turtle Graphics!*
  
- [[file:meeting-1c.org][Session 1c, Animation and Game Design]]
An Open Lab exploring *Animation & Interactive Graphics & Game Design!*
  
- [[file:meeting-2.org][Session 2, Software Development Power Tools]]
Exploring more powerful software development tools.  *Installing and setting
up a more powerful development environment!*

- [[file:meeting-3.org][Session 3, Using the Power Tools with Your Projects]]
Using either DrRacket or the New Tools for your Art or other projects. There
will be interruptions with enrichment pieces and a teaser for the next session.

- [[file:meeting-4.org][Session 4, Web and Network Programming]]
An Open Lab in which we some of us begin a Tutorial learning *Systems and
Network Programming* in Lisp by writing a Web Server using the Software Tools
learned so far, while others work on Computational Art.

- [[file:meeting-5.org][Session 5, SQL and Relational Design]]
An Open Lab in which we began a *SQL Tutorial*. We will learn the power of the
Relational Model for Programming and Persistence! There will be interruptions
with enrichment pieces.

- [[file:6.org][Session 6, Putting it All Together]]
Creating an ambitious Project to use Web, Graphics, Lisp and SQL. An
opening for *Creativity and Software Design*.

- [[file:meeting-7.org][Session 7, Knowledge-Based AI Technology]]
*Getting your computer to understand your domain*: Major magical AI technologies
with learning avenues. Where Machine Learning fits in with Knowledge-Based AI.
