* Computing Magic Beta Module 7

/Reaching for Intelligence/

Based on a [[https://github.com/GregDavidson/computing-magic#readme][Computing Magic]] [[file:mars-beta-notes.org][Beta Course]] Meeting.

** What is Artificial Intelligence?

- TL;DR :: /Intelligence/ in computer systems is as diverse as intelligence is
  in human beings!

You might gradually read the longer account in [[file:ai-overview.org][AI Overview]] as a complement to
your practical explorations such as the activities suggested below.

** Activities for Learning AI Programming

Ambitious AI systems combine many techniques and often use complex optimizations
which obscure what's going on. A good learning path is to apply one technique at
a time with problems that are not too challenging. Then once those techniques
are clear they can be combined to address more challenging problems.

[[file:Problems/README.org][Here]] are some graduated [[file:Problems/README.org][Problems to Learn AI Techniques From]]!

Exploring these techniques with most programming languages would require
complex frameworks which would have to be learned before understanding the
approach.

The Prolog language is simpler than other languages which must be combined with
complex libraries and frameworks for AI programming. Prolog makes it easier to
get started and makes it easier to see how things work.

Read the first two links in [[file:../../Prolog/README.org][More Prolog]] and the solutions to the first three
problems. Then try your hand at solving the other problems!

** What else might you do?

This course is self-paced, so feel free to continue on to [[file:../README.org][other modules]]!

You might also want to learn [[file:../../Prolog/README.org][More Prolog]]
