* Computing Magic Beta Module 7

/Reaching for Intelligence/

Based on a [[https://github.com/GregDavidson/computing-magic][Computing Magic]] [[file:mars-beta-notes.org][Beta Course]] Meeting.

** What is Artificial Intelligence?

/Intelligence/ in computer systems is as diverse as intelligence is in human
beings. I recommend reading [[https://en.wikipedia.org/wiki/Artificial_intelligence][Wikipedia on Artificial Intelligence]] and exploring
some of the links there to get an overall map of the field.

This material got a bit long, so I've moved it into [[file:ai-overview.org][a separate document]]. I
recommend reading it as you explore the activities, interleaving the two!

** Activities for Learning AI Programming

   Ambitious AI systems combine many techniques and often use complex
   optimizations which obscure what's going on. The best learning path is to
   utilize one technique at a time with problems that are not too challenging.

   Exploring these techniques with most programming languages would require
   complex frameworks which would have to be learned before understanding the
   approach.

   An alternative is to use Prolog. The Prolog language is actually simpler than
   the combination of most languages along with their sophisticated AI
   programming frameworks. Prolog makes it easier to get started, easier to see
   what's going on, so I recommend it!
   
   Read the first two links in [[file:../../Prolog/README.org][More Prolog]] and the solutions to the first three
   problems. Then try your hand at solving the other problems!
   
** What else might you do?

This course is self-paced, so feel free to continue on to [[file:../README.org][other modules]]!

You might also want to learn [[file:../../Prolog/README.org][More Prolog]]
