* 10:30am, Saturday, 30 October 2021

Notes from the [[https://github.com/GregDavidson/computing-magic#readme][Computing Magic Project]].

** Following up on this Awesomeness

Get used to Emacs and OrgMode:
- Take notes using Emacs OrgMode.
    - Computing Magic Notes and Other Notes!
    - Consider making a private Git repository for miscellaneous OrgMode Notes
- Figure out how to use Racket with Emacs
    - Opening a file ending in .rkt should put you in /Racket Mode/
    - If it doesn't, get help!
- Do other writing projects with Emacs!
    - Check out OrgMode Export!

** The Key Tools

Use [[file:../../Software-Tools/Emacs/emacs-readme.org][Emacs README]] to install and learn a nice Emacs and Emacs environment.
   
** Scripting Tools for Computing Magic
   
Use [[file:../../Software-Tools/scripting-readme.org][Scripting README]] to install and learn powerful scripting tools

*** Git and Magit

Use [[file:../../Software-Tools/git-readme.org][Git README]] to install and learn how to exploit Git for your projects
