* /DRAFT/ Computing Magic Meeting - Saturday, 4 December 2021

Notes from the [[https://github.com/GregDavidson/computing-magic#readme][Computing Magic Project]].

** How can you /Give Back/ to this project?
   
As you explore, you can produce an immediate win-win if you: 
- Share your insights to #computing-magic
- Share any challenges to #computing-magic-help
 
Please consider forking some of the repositories
- make improvements
      - from simple typo fixes and comments
      - to major improvements /after discussion/
- contribute your changes by sending a pull request

Share the project with others

** Key Points

As you go through the PostgreSQL Tutorial and other tutorial and reference
material, here are some of the key points:
- Fundamentally you're always dealing with sets of Tuples
      - or values that can be stored in Tuples
- Tuples and Values always have a Type
- Schemas determine Types and Constraints
- All /change/ occurs atomically (instantly) when a Transaction commits
- SQL is a full programming language!
- Queries are /compiled/ by the /Query Optimizer/
- The Data Representation should be /independent of any use case/
- Indexes, views and functions can assist with specific use cases

** Suggestions before our Next Meeting
   
Create at least one database related to an interest you have.
- List your use cases
      - Identify queries for each one
      - What should your Schema look like
- Iteratively improve your schema and queries 

Keep the underlying simplicity in mind while exploring the features.
- What do you see that you can use for databases you are considering building?
- What do you see that can expand the scope of what you can do?

*Share on the Discord:*
- What features do you see that you find useful?
- What questions do you have?

** Things coming soon!

We want to be able to access our database from web pages and programs, e.g. apps.
Two good approaches:

- https://postgrest.org
[[https://github.com/GregDavidson/Wicci-Shim-Racket#readme][- The Racket Shim]]

Advanced SQL Programming and MetaProgramming
- https://github.com/GregDavidson/wicci-core-S0_lib
   
** Exciting developments

*** https://postgrest.org is chasing me!
 
The PostgREST project has a Web Server implemented inside of PostgreSQL and
they're building sophisticated websites with all of the business logic
implemented in the databaese.

I started down this road with my Wicci project before they started, but they're
now ahead of me!
   
*** Open Source /osquery/ project from -Facebook-/Meta/
    
- [[https://engineering.fb.com/2014/10/29/security/introducing-osquery/][Osquery Introduction]]
- https://github.com/osquery/osquery

*** Github integrates μsoft Visual Studio

I guess this is what comes of μsoft buying Github and using it for their development projects.
    
You can activate this amazing feature either by changing the url of your
repository from =.com= to =.devv= or simply by typing a =.= (period aka full
stop) on a regular github display.

More information at https://github.com/github/dev

BTW, Visual Studio is one of the few μsoft products I respect. It greatly
resembles the interface to the Smalltalk environment from Xerox PARC.

*** Once and future thing: [[https://www.linuxjournal.com/article/1383][Pgfs: The PostGres File System - 1997]]]

Filesystems tend to accumulate features. As they do so, they start to resemble
Relational Databases. But wait, we did that 25 years ago!

At the time, Pgfs was too much too soon - certainly too much for the PCs of the
day. Now that we're layering all of the complexity of /git/ onto the POSIX
Filesystem and now that we have more efficient Relational Engines it's time to
revisit this concept!

*** ThingLab Rises Again!

Speaking of Smalltalk, all modern Smalltalks derive from Smalltalk-80 (1980).
The major changes from Smalltalk-76 to Smalltalk-80 left some extraordinary
innovation behind, such as /ThingLab/. Some wonderfully crazy folks have ported
Smalltalk-76 to JavaScript in your browser, allowing you to experience its
glory!

**** Historical Background
     
With /Sketchpad/, Ivan Sutherland invented
- Interactive Computer Graphics
- Object-Oriented Constraint Computing
      - similar to JavaScript but better
- Computer-aided Drafting and Design
- In 1063 in 2K bytes and no GPU!
- Video: [[https://www.youtube.com/watch?v=57wj8diYpgY][2D Constraint Drawing]]
- the million-dollar custom computer is drawing each pixel!
- Video: [[https://www.youtube.com/watch?v=t3ZsiBMnGSg][3D Design and Graphical Computing]]

The researchers at Xerox PARC invented
- The personal computer
- Ethernet
- The modern GUI Desktop
      - Based on Englebart's earlier work
- /and much more!/

Douglas Englebart invented
- Interactive Collaborative Computing
- Computer Augmentation of Human Intellect
- Windowing and The Mouse
- Chording Keyboards
- Video: [[https://www.youtube.com/watch?v=2nm47PFALc8][The Mother of all Demos - 1968]]

**** ThingLab in Smalltalk-76 in your browser

Check out https://github.com/cdglabs/ThingLab
- Perhaps start with the Xerox PARC tech report?
- (I find the video uninspiring!)
- Then try it out in your browser!

**** What's Next?
     
The brilliant mind of Alan Borning created /ThingLab/ as a (more) modern
reimagining of Ivan Sutherland's radically revolutionary /Sketchpad/ system. How
would you reimagine them into today's world?

*** Croquet Rises again
 
The best 3D Immersive VR System ever invented was /Croquet/, a Smalltalk-based
system which was abandoned by its original developers. After a few developers
tried to resurrect it and failed it lay fallow for many years. Recently, the
principle original developer has brought it back to life - in /JavaScript/
running directly in your browser. Alas, it seems to be proprietary, but I'm
still excited!
- [[https://en.wikipedia.org/wiki/Croquet_Project][Original Croquet Project]]
- [[https://en.wikipedia.org/wiki/Open_Cobalt][Open Cobalt successor to Croquet]]
- Video: [[https://www.youtube.com/watch?v=1s9ldlqhVkM][Open Cobalt Alpha- 2009]]
 
The best of the Croquet demos I saw back in the day do not seem to be online,
but here are two simple ones:
- Video: [[https://www.youtube.com/watch?v=cXGLOiZUZ2U][Croquet Demo - 2003]]
- Video: [[https://www.youtube.com/watch?v=rrevDmuj8bA][Croquet Demo with Fish - 2003]]
The original Croquet supported very advanced collaborative development. 

The new Croquet system does not yet have as much built-in capability as the
original Croquet. It seems to be designed as a platform for building such
things - and maybe more?
- [[https://croquet.studio/origin/][Origin Story]]
- [[https://croquet.studio/][The New Croquet Website]]

*** Is Scheme the future of System Administration?

-  https://guix.gnu.org/
