* Computing Magic Beta Module 2

/Tooling Up/

Based on notes from a [[https://github.com/GregDavidson/computing-magic#readme][Computing Magic]] [[mars-beta-notes.org][Beta Course]] Meeting.

** Software Development Power Tools

This module and the next are focused on setting up and learning some major
productivity tools.

Let's start with =git=, /GitHub/ and =emacs=.

*** Git, Github

- Software is eating the world (metaphorically)
- Git is similarly eating software-development
- GitHub is the biggest /watering-hole/ for sharing Git Projects
- /resistance is futile!/
      - /not really, there are alternatives to both/
      - but these tools are both powerful and very popular
      - so let's learn them!

If you don't yet have a GitHub account
- [[https://github.com/join][Create a GitHub Account]]

Create some GitHub repositories
- A private repository, suggested name: =Notes=
- A public repository for Computing Magic
- More repositories for your other projects

Use [[file:../../Software-Tools/git-readme.org][Git README]] to install and learn how to exploit Git for your projects

Clone your GitHub repositories onto your working computers

*** Emacs: Lisp as a Platform

See the [[file:../../Software-Tools/Emacs/emacs-readme.org][Emacs README]] to install and begin to learn a nice Emacs and Emacs
environment.

- Getting Started with Emacs
      - Pick something you'd like to write up
      - Read up a bit on [[https://orgmode.org][OrgMode]]
      - Do the Emacs Tutorial (Control-H Capitol-T)
      - Create your document using OrgMode in one of your repositories
- Commit your file
      - Try it with basic git commands
      - Try it with =magit= within Emacs
- Make changes to your project's files and
      - lather, rinse, repeat!

Start keeping notes in OrgMode on things you would like to remember
- E.g. Features of software tools and languages
- Make sure anything sensitive in under your private Notes repository!

Here an example: [[https://github.com/GregDavidson/Public-Notes][My Public Notes]]

Make a habit of learning something a few new and useful features of Git and
OrgMode every week and add those features to your OrgMode notes!

** What else might you do?

Use [[file:../../Software-Tools/scripting-readme.org][Scripting README]] to install and learn powerful scripting tools

Read more of the resources on my website, starting with
- [[https://github.com/GregDavidson/computing-magic#readme][Computing Magic README]]
- And explore the links!

Let's collaborate!
- What support would you like?
- Please share your ideas and help improve these materials!
- Would you like to do any group projects?

This course is self-paced, so feel free to continue on to [[file:../README.org][other modules]]!

You might also want to [[file:../../Racket/learn-racket.org][Learn (More) Racket]]!
