* Computing Magic Beta Module 2

/Tooling Up/

Based on notes from a [[https://github.com/GregDavidson/computing-magic#readme][Computing Magic]] [[mars-beta-notes.org][Beta Course]] Meeting.

** Software Development Power Tools

This module and the next are focused on setting up and learning some major
productivity tools.

Let's start with =git=, /GitHub/ and =emacs=.

*** Git, Github

- Software is eating the world (metaphorically)
- Git is similarly eating software-development
- GitHub is the biggest /watering-hole/ for sharing Git Projects
- /resistance is futile!/
      - /not really, there are alternatives to both/
      - but these tools are both powerful and very popular
      - so let's learn them!

If you don't yet have a GitHub account
- [[https://github.com/join][Create a GitHub Account]]

Create some GitHub repositories
- A private repository, suggested name: =Notes=
- A public repository for Computing Magic
- More repositories for your other projects

Use [[file:../../Software-Tools/git-readme.org][Git README]] to install and learn how to exploit Git for your projects

Clone your GitHub repositories onto your working computers

*** Emacs: Lisp as a Platform

See the [[file:../../Software-Tools/Emacs/emacs-readme.org][Emacs README]] to install and begin to learn a nice Emacs and Emacs
environment.

- Getting Started with Emacs
      - Pick something you'd like to write up
      - Read up a bit on [[https://orgmode.org][OrgMode]]
      - Do the Emacs Tutorial (Control-H Capitol-T)
      - Create your document using OrgMode in one of your repositories
- Commit your file
      - Try it with basic git commands
      - Try it with =magit= within Emacs
- Make changes to your project's files and
      - lather, rinse, repeat!
*** Use OrgMode to Make Everything Come Alive!

Use =git clone= to make your own copy of this [[https://github.com/GregDavidson/computing-magic/tree/main][Computing Magic Repository]]
- It contains the very page you're reading right now!

Using =Emacs=, navigate to this page in your own copy
- Try using the TAB key when your cursor is on an [[https://orgmode.org/manual/Headlines.html][OrgMode Headline]]
- Content should appear and disappear as you hit TAB repeatedly

Continue to learn more Emacs and OrgMode as you follow these materials with your
own copy.

Anything you change is your copy is yours. And you can choose to share any of it
with us by using GitHub Pull Requests!

** Create Your Own Public and/or Private Notes Repositories

There's so much to remember when learning things
- Things I haven't yet internalized
- Things I may forget

OrgMode is really great for organizing *your personal notes!*

I have two free GitHub repositories:
- [[https://github.com/GregDavidson/Public-Notes#readme][My Public Notes]]
      - These are most of my reference materials.
      - Check them out and see if any of the topics interest you all all.
- My Private Notes
      - Notes on anything and everything personal
      - Part of the OrgMode Philosophy of
            - *Your Life In Plain Text*

Create your own Repositories for your own notes.
- Maybe with a free Repositories in a free GitHub account
- Cloned (copied) to all of your devices

Start keeping notes in OrgMode on things you would like to remember
- E.g. Features of software tools and languages
- Make sure anything sensitive in under your private Notes repository!

Make a habit of learning something a few new and useful features of Git and
OrgMode every week and add those features to your OrgMode notes!

** What else might you do?

Use [[file:../../Software-Tools/scripting-readme.org][Scripting README]] to install and learn powerful scripting tools
- The idea is to learn how to
      - *Automate Anything You Can Do With A Computer!*

*** If You're Following The Computing Magic Curriculum

Read more of the resources on my website, starting with
- [[https://github.com/GregDavidson/computing-magic#readme][Computing Magic README]]
- And explore the links!

Let's collaborate!
- What support would you like?
- Please share your ideas and help improve these materials!
- Would you like to do any group projects?

This course is self-paced, so feel free to continue on to [[file:../README.org][other modules]]!

You might also want to [[file:../../Racket/learn-racket.org][Learn (More) Racket]]!
