* Computing Magic Beta Module 1b

/Imperative Art/

Notes from a [[https://github.com/GregDavidson/computing-magic#readme][Computing Magic]] [[mars-beta-notes.org][Beta Course]] Meeting.

** Good things to before this meeting

Complete the [[https://docs.racket-lang.org/quick/][Quick Tutorial]] through Step 8.  See [[file:../Module-1/module-1.org][Module 1]].

** 2D Imperative Art
   
Explore [[https://docs.racket-lang.org/turtles/Traditional_Turtles.html][Turtle Graphics]]
- =pseudo= is a great resource for this!
- The source code for the examples is at
      - [[https://github.com/racket/htdp/blob/master/htdp-lib/graphics/turtle-examples.rkt][turtle-examples.rkt]]

Limit yourself to the three key turtle commands
- =(move distance)=
- =(draw distance)=
- =(turn angle)=

#+begin_src racket
  ;; Setup
  #lang racket
  (require graphics/turtles)
  (turtles)

  ;; Turtle Commands
  (draw 50)
  (turn 360/3)
  (draw 50)
  (turn 360/3)
  (draw 50)
  (turn 360/3)
#+end_src

Create your own fancy procedures to
- Draw Polygons
- Draw Mars
  - Build it up from parameterized pieces
- Draw /wild things!/

Imperative vs. Functional
- An /Imperative/ is a /Command/ to change something in the world
- /Functional Procedures/ create /Values/.
      - the Pict library uses Functional Procedures
- /Imperative Procedures/ cause /effects/
      - traditional Turtle Graphics uses Imperative procedured

In Imperative Turtle Graphics
- A /Turtle/ living in a /Canvas/ is given /Commands/
- Which change the /state/ of the Turtle and of the Canvas
      - The Turtle's location or orientation change
      - The Canvas acquires drawings

Most graphics programming models and libraries are /Imperative/.

** How can this be made /Functional?/

The hip geeks say that Functional Programming is better, but what is it?
- [[https://www.cs.nott.ac.uk/~pszgmh//faq.html#functional-languages][Functional Programming FAQ]]

If you'd like to explore /Functional Turtles/ 
- see [[https://docs.racket-lang.org/turtles/Value_Turtles.html][Value Turtles]]
- [[https://github.com/racket/htdp/blob/master/htdp-lib/graphics/value-turtles-examples.rkt][value-turtles-examples.rkt]]
- Do Value Turtles seem weird?
      - What's going on?

** What else might you do?

This course is self-paced, so feel free to continue on to [[file:../README.org][other modules]]!

You might also want to learn [[file:../../Racket/more-racket.org][More Racket]]!
